export const constants = {
  langz: {
    eng: {
      dir: "ltr",
      otp: {
        title:
          "Please enter the verification code received on mobile number xxxxxx0236 to enter GAZT portal",
        verifyTitle: "Resend Verification code",
      },
      signup: {
        title: "Create New Account",
        subtitle: {
          t1: "Company",
          t2: "Establishment",
          t3: "Individuals",
          t4: "other",
        },
      },
      individual: {
        title: "New Individual Account",
        header: {
          h1: "Individual Register",
          h2: "Review Information",
          h3: "Password",
        },

        c1: {
          title: "Individual register",
          in1: "ID Type",
          in2: "ID Number",
          in3: "Date of Birth",
          btn: "Continue",
        },
        c7: {
          title: "Individual register",
          in1: "ID Type",
          in2: "ID Number",
          in3: "Name",
        },
        c2: {
          title: "National Address",
          in1: "City",
          in2: "Nighhborhood",
          in3: "Street Name",
          in4: "Postal Code",
          in5: "Building Number",
          in6: "Unit Number",
          btn: "Continue",
        },
        c3: {
          title: "Contact Information",
          in1: "Mobile Number",
          in2: "Email",
          btn: "Continue",
        },
        c4: {
          title: "Create New Password",
          in1: "New Password",
          in2: "Confirm New Password",
          subtitle: {
            t1: "Password Strength:",
            t2: "Strong",
            t3: "Password should not be less than 8 characters",
            t4: "Not exceed 16 characters",
            t5: "English capital and small letters",
            t6: "Numbers and symbols",
          },
        },
        c5: {
          title: "I agree with these Terms & Conditions and to proceed further",
          btn: "Confirm",
        },
        c6: {
          t1: "Registration Successful ",
          t2: "You have Successfully registered to GAZT Services",
          t3: "You have received an SMS with the TIN number.",
          t4:
            "You can use the TIN number and the set password to login in future",
          btn: "Go To Dashboard",
        },
      },
      vat: {
        title: "Register in VAT",
        header: {
          h1: "Taxpayer Details",
          h2: "Financial Details",
          h3: "Declaration",
        },
        c1: {
          title: "Taxpayer Details",
          t1: "VAT Eligible Start Date",
          t2: "Import or Export",
          t3: "Import",
          t4: "Export",
          t5: "Import & Export",
        },
        c2: {
          title: "Account",
          t1: "Select your Bank account",
          t2: "SA32...…………………………………………………………54",
          t3: "SA32...…………………………………………………………33",
          btn: "Add New Account",
          btn2: "Continue",
        },
        c3: {
          title: "Sales Details",
          t1:
            "In the upcoming 12 months [Including this month],What will be your total VAT taxable sales value?",
          t2:
            "For the last 12 months [at the time of registration],What was your total VAT taxable sales value?",
        },
        c4: {
          title: "Expenses Details",
          t1:
            "In the upcoming 12 months [Including this month],What will be your total VAT taxable Expenses value?",

          t2:
            "For the last 12 months [at the time of registration],What was your total VAT taxable Expenses value?",
          t3: "Less than",
          t4: "187,500 SAR",
          t5: "More than or equal to",
          t6: "187,500 SAR",
        },
        c5: {
          title: "Supporting Documents",
          t1:
            "Attachments are mandatory for Non-Eligible Taxpayers*Please submit the supporting documents as proof of your VAT eligibility. Otherwise, it is highly likely that you will be audited over the course of next 6 months.",
          t2:
            "Type of document that you are submitting to prove whether or not eligible.",
          t3: "Income Statement",
          t4: "Customs Report",
          t5: "Audited Reports",
          t6: "Official Contracts",
          t7: "Attached Document",
          t8: "File Name",
          btn: "Add New Attachment",
          btn2: "Continue",
        },
        c6: {
          t1:
            "I Hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct.",
          t2: "ID type",
          t3: "ID Number",
          t4: "Date",
          t5: "Name",
          t6:
            "I hereby declare that the above mentioned information is true and correct to the best of my knowledge and belief",
        },
        c7: {
          t1: "I agree with this",
          t2: "and proceed further",
          btn: "Continue",
        },
        c8: {
          t1: "VAT  Registration Request Successful ",
          t2: "GAZT Acknowledges Your VAT Registration application",
          t3: "Name:",
          t4: "Ahmad Muhammed",
          t5: "Application Number:",
          t6: "1234567890",
          t7: "Date:",
          t8: "23/6/2020",
          t9:
            "Please retain this number for future reference and communication. GAZT will process your request and if needed  contact you. For further information, please contact Help Desk",
          btn: "Download Acknowledgement ",
          btn2: "Go To Dashboard",
        },
        c9: {
          title: "Financial Representative",
          t1:
            "This section is Mandatory for Non-Resident, For residents, you can skip this section or enter the below details.",
          t2: "TIN ",
          t3: "ID Type*",
          t4: "ID Number*",
          t5: "Date of Birth*",
          t6: "First Name*",
          t9: "Last Name*",
          t7: "Mobile Number*",
          t8: "Email*",
        },
      },
      excise: {
        title: "Register in Excise Tax ",
        header: {
          h1: "Taxpayer Details",
          h2: "Excise Details",
          h3: "Declaration",
        },
        c1: {
          title: "Taxpayer Details",
          t1: "TIN",
          t2: "IBAN",
          t3: "Commercial Name",
        },
        c2: {
          title: "Attachments",
          t1: "Commercial registration to be register for Excise Tax",
          t2: "CR Number 1",
          t3: "CR Number 2",
          t4: "CR Number 3",
          t5: "CR Number Documents",
          t6: "Attached Document",
          t7: "Attached Other Document",
          btn: "Add CR Number",
        },
        c3: {
          title: "Contact Person Details",
          t1: "ID Type",
          t2: "ID Number",
          t3: "Date of Birth",
          t4: "Name",
          t5: "Mobile number",
          t6: "Email",
          btn: "",
        },
        c4: {
          title: "Address Details",
          t1: "Building Number",
          t2: "Street Name",
          t3: "Nighbrhood",
          t4: "Postal Code",
          t5: "Additional Number",
          t6: "Region",
          t7: "City",
          btn: "Continue",
        },
        c5: {
          title: "Excise Details",
          t1: "What kind of Excise Tax activities to be licensed?",
          t2: "Import Excise goods",
          t3: "Type 2",
          t4: "Type 3",
          t5: "Type 4",
          t6:
            "What was your total VAT taxable expenses value for the last 12 months at the time of registration?",
          t7: "Type one",
          t8: "Energy Drinks",
          t9: "Tobacco & Related Products",
          t10: "Do you want to apply for Tax Warehouse?",
          t11: "Yes",
          t12: "NO",
          btn: "Continue",
        },
        c6: {
          t1:
            "I Hereby certify that I am authorized to complete this form for the taxable person and that all information contained is correct.",
          t2: "Contact Person Name",
          t3: "Designation",
          t4: "ID type",
          t5: "ID Number",
          t6: "Date of Birth",
          t7: "Date",
          t8:
            "The undersigned is authorized to submit this form as per Excise Tax regulations and promises that all information contained herein is true and correct",
        },
        c7: {
          t1: "I agree with this Conditions and proceed further",
          btn: "Confirm",
        },
        c8: {
          t1: "Registration For Excise Tax Successful ",
          t2: "GAZT Acknowledges Your Registration For Excise Tax",
          t3: "Name:",
          t4: "Ahmad Muhammed",
          t5: "Application Number:",
          t6: "1234567890",
          t7: "Date:",
          t8: "23/6/2020",
          t9:
            "Please retain this number for future reference and communication. GAZT will process your request and if needed  contact you. For further information, please contact Help Desk",
          btn: "Download Acknowledgement ",
          btn2: "Go To Dashboard",
        },
      },
      dashboard: {
        title: "Quick Actions",
        subtitle: {
          t1: "VAT Return",
          t2: "Tax Certificates",
          t3: "Bill Payments",
          t4: "Zakat Return",
        },
        title2: "Bills",
        title3: "Returns",
        title4: "Tax Types",
        subtitle2: {
          t1: "VAT",
          t2: "Excesie",
          t3: "Zakat",
          t4: "Witholding",
        },
        title5: "Help",
        subtitle3: {
          t1: "Contact Us",
          t2: "FAQs",
          t3: "Chat",
        },
        title6: "Inbox",
        subtitle4: {
          t1: "Mail Title 1",
          d1: "Mail Description can ...",
        },
        title7: "Commitments",
        subtitle5: {
          t1: "Upcoming com.....1",
          d1: "Commitment Details..",
        },
      },
    },
    arb: {
      dir: "rtl",
      otp: {
        title:
          "الرجاء إدخال رمز التحقق المرسل من خلال الرسائل النصية على رقم الجوال للدخول إلى البوابة الإلكترونية xxxxxx0236",
        verifyTitle: "إعادة إرسال رمز التحقق",
      },
      signup: {
        title: "انشاء حساب جديد",
        subtitle: {
          t1: "شركة",
          t2: "مؤسسة",
          t3: "فردي",
          t4: "آخرى",
        },
      },
      dashboard: {
        title: "الوصول السريع",
        subtitle: {
          t1: "إقرارات ضريبة القيمة المضافة",
          t2: "الشهادات الضريبية",
          t3: "دفع الفواتير",
          t4: "دفع الفواتير",
        },
        title2: "الفواتير",
        title3: "الإقرارات",
        title4: "أنواع الضرائب",
        subtitle2: {
          t1: "ضريبة القيمة المضافة",
          t2: "ضريبة السلع الإنتقائية",
          t3: "الزكاة",
          t4: "ضريبة الاستقطاع",
        },
        title5: "المساعدة",
        subtitle3: {
          t1: "تواصل معنا",
          t2: "الأسئلة الشائعة",
          t3: "المحادثة",
        },
        title6: "صندوق الوارد",
        subtitle4: {
          t1: "عنوان البريد",
          d1: "محتوى البريد...........",
        },
        title7: "الإلتزامات",
        subtitle5: {
          t1: "لاتوجد إلتزامات قادمة",
          d1: "محتوى البريد...........",
        },
      },
      individual: {
        title: "حساب فردي جديد",
        header: {
          h1: "التسجيل الفردي",
          h2: "عرض المعلومات",
          h3: "كلمة المرور",
        },
        c1: {
          title: "التسجيل الفردي",
          in1: "نوع الهوية",
          in2: "رقم الهوية",
          in3: "تاريخ الميلاد",
          btn: "استمر",
        },
        c7: {
          title: "التسجيل الفردي",
          in1: "نوع الهوية",
          in2: "رقم الهوية",
          in3: "تاريخ الميلاد",
        },
        c2: {
          title: "العنوان الوطني",
          in1: "المدينة",
          in2: "الحي",
          in3: "اسم الشارع",
          in4: "الرمز البريدي",
          in5: "رقم المبنى",
          in6: "رقم الوحدة",
          btn: "",
        },
        c3: {
          title: "بيانات التواصل",
          in1: "رقم الجوال",
          in2: "البريد الإلكتروني",
          btn: "استمر",
        },
        c4: {
          title: "انشاء كلمة المرور الجديدة",
          in1: "كلمة المرور الجديدة",
          in2: "تأكيد كلمة المرور الجديدة",
          subtitle: {
            t1: "قوة كلمة المرور:",
            t2: "قوية",
            t3: "يجب ألا تقل كلمة المرور عن 8 أحرف",
            t4: "كلمة المرور لا تتجاوز 16 حرفًا",
            t5: "كلمة المرور يجب أن تحتوي أحرف كبيرة وصغيرة بالغة الإنجليزية",
            t6: "أرقام ورموز",
          },
        },
        c5: {
          title: "أوافق على هذه الشروط والأحكام ",
          btn: "تأكيد",
        },
        c6: {
          t1: "تم التسجيل بنجاح",
          t2: "لقد تم التسجيل بنجاح في خدمات الهيئة العامة للزكاة والدخل",
          t3: " تم إرسال رسالة نصية قصيرة تحوي الرقم المميز ",
          t4:
            "يمكنك استخدام الرقم المميز وكلمة المرور المُدخله مسبقاً لتسجيل الدخول في المستقبل",
          btn: "الذهاب إلى لوحة التحكم",
        },
      },
      vat: {
        title: "التسجيل في ضريبة القيمة المضافة",
        header: {
          h1: "تفاصيل المكلف",
          h2: "تفاصيل ضريبة القيمة المضافة",
          h3: "التعهد",
        },
        c1: {
          title: "تفاصيل المكلف",
          t1: "تاريخ بداية الخضوع لضريبة القيمة المضافة",
          t2: "مستورد أو مصدر",
          t3: "مستورد",
          t4: "مصدر",
          t5: "مستورد ومصدر",
        },
        c2: {
          title: "الحساب البنكي",
          t1: "الرجاء اختيار رقم الحساب البنكي",
          t3: "SA32...…………………………………………………………54",
          t4: "SA32...…………………………………………………………33",
          btn: "إضافة حساب جديد",
          btn2: "متابعه",
        },
        c3: {
          title: "تفاصيل المبيعات",
          t1:
            "في الـ 12 شهرًا القادمة [بما في ذلك هذا الشهر] ، ما القيمة الإجمالية للمبيعات الخاضعة لضريبة القيمة المضافة؟",
          t2:
            "خلال آخر 12 شهرًا [وقت التسجيل] ، ما هو إجمالي قيمة المبيعات الخاضعة للضريبة على ضريبة القيمة المضافة؟",
        },
        c4: {
          title: "تفاصيل المصروفات",
          t1:
            "خلال الـ 12 شهرًا القادمة [بما في ذلك هذا الشهر] ، ما قيمة إجمالي النفقات الضريبة على ضريبة القيمة المضافة؟",
          t2:
            "خلال آخر 12 شهرًا [في وقت التسجيل] ، ما هي قيمة إجمالي نفقاتك الضريبة على ضريبة القيمة المضافة؟",
          t3: "أكثر من أو يساوي",
          t4: "ر.س 187,500 ",
          t5: "أقل من",
          t6: " 187,500 ر.س",
        },
        c5: {
          title: "المرفقات",
          t1:
            "المرفقات إلزامية للمكلفين (الغير خاضعين) الرجاء تقديم المستندات المطلوبة لإثبات أحقيتك بالتسجيل في ضريبة القيمة المضافة , وفي حالة عدم تقديم تلك المستندات , فمن المرجح أن تتم عملية التدقيق على مدى 6 أشهر المقبلة .",
          t2: "نوع المستندات المقدمة لإثبات أحقيتك بالتسجيل",
          t3: "عقد رسمي",
          t4: "تقارير مدققة",
          t5: "بيانات الجمارك",
          t6: "قائمة الدخل",
          t7: "الملف المرفق",
          t8: "File Name",
          btn: "إضافة مرفق جديد",
          btn2: "متابعه",
        },
        c6: {
          t1:
            "أقر بموجب هذا أنني مفوض لاستكمال هذا النموذج للشخص الخاضع للضريبة وأن جميع المعلومات الواردة صحيحة.",
          t2: "نوع الهوية",
          t3: "رقم الهوية",
          t4: "التاريخ",
          t5: "الاسم",
          t6:
            "المفوضين أدناه مخولون بتقديم هذا النموذج وفقًا للوائح ضريبة السلع الانتقائية وأن جميع المعلومات الواردة في هذه الوثيقة صحيحة ودقيقة",
        },
        c7: {
          t1: "أوافق على هذه",
          t2: "والأحكام",
          btn: "المتابعه",
        },
        c8: {
          t1: "تم التسجيل في ضريبة القيمة المضافة بنجاح",
          t2:
            "تقر الهيئة العامة للزكاة والدخل بتسجيلك في ضريبة السلع الانتقائية",
          t3: "الاسم",
          t4: "Ahmad Muhammed",
          t5: "رقم الطلب",
          t6: "1234567890",
          t7: "التاريخ:",
          t8: "23/6/2020",
          t9:
            "يرجى الاحتفاظ برقم الطلب للرجوع إليه والتواصل من خلاله . ستقوم الهيئة بمعالجة الطلب الخاص بك . لمزيد من المعلومات ، يرجى الاتصال بخدمة العملاء",
          btn: "تنزيل الإقرار",
          btn2: "الذهاب إلى لوحة التحكم",
        },
        c9: {
          title: "Financial Representative",
          t1:
            "This section is Mandatory for Non-Resident, For residents, you can skip this section or enter the below details.",
          t2: "TIN ",
          t3: "ID Type*",
          t4: "ID Number*",
          t5: "Date of Birth*",
          t6: "First Name*",
          t9: "Last Name*",
          t7: "Mobile Number*",
          t8: "Email*",
        },
      },
      excise: {
        title: "التسجيل في ضريبة السلع الانتقائية",
        header: {
          h1: "تفاصيل دافع الضرائب",
          h2: "تفاصيل ضريبة السلع الانتقائية",
          h3: "التعهد",
        },
        c1: {
          title: "تفاصيل دافع الضرائب",
          t1: "الرقم المميز",
          t2: "رقم الايبان",
          t3: "الاسم التجاري",
        },
        c2: {
          title: "المرفقات",
          t1: "السجلات التجارية المسجلة المتعلقة بالضريبة الإنتقائية",
          t2: "وثائق السجلات التجارية",
          t3: "الملف المرفق",
          t4: "إرفاق مستند آخر",
          t5: "",
          t6: "",
          btn: "إضافة رقم سجل تجاري",
        },
        c3: {
          title: "تفاصيل جهة الاتصال",
          t1: "نوع الهوية",
          t2: "رقم الهوية",
          t3: "تاريخ الميلاد",
          t4: "الاسم",
          t5: "رقم الجوال",
          t6: "البريد الإلكتروني",
        },
        c4: {
          title: "تفاصيل العنوان",
          t1: "الحي",
          t2: "اسم الشارع",
          t3: "رقم البناية",
          t4: "الرمز البريدي",
          t5: "الرقم الإضافي",
          t6: "المنطقة",
          t7: "المدينة",
          btn: "المتابعه",
        },
        c5: {
          title: "تفاصيل ضريبة السلع الانتقائية",
          t1: "ما نوع الأنشطة الضريبية المطلوب ترخيصها؟ ",
          t2: "Import Excise goods",
          t3: "Type 2",
          t4: "Type 3",
          t5: "Type 4",
          t6:
            "ما هو إجمالي قيمة ضريبة القيمة المضافة الخاضع للضريبة خلال 12 شهرا الماضية من بداية التسجيل؟",
          t7: "Type one",
          t8: "مشروبات الطاقة",
          t9: "التبغ والمنتجات ذات الصلة",
          t10: "هل تريد مخازن ضريبية؟",
          t11: "نعم",
          t12: "لا",
          btn: "المتابعه",
        },
        c6: {
          t1:
            "أقر بموجب هذا أنني مفوض لاستكمال هذا النموذج للشخص الخاضع للضريبة وأن جميع المعلومات الواردة صحيحة.",
          t2: "اسم جهة الاتصال",
          t3: "المنصب",
          t4: "نوع الهوية",
          t5: "رقم الهوية",
          t6: "تاريخ الميلاد",
          t7: "التاريخ",
          t8:
            "المفوضين أدناه مخولون بتقديم هذا النموذج وفقًا للوائح ضريبة السلع الانتقائية وأن جميع المعلومات الواردة في هذه الوثيقة صحيحة ودقيقة",
        },
        c7: {
          t1: "أوافق على هذه",
          t2: "والأحكام",
          btn: "المتابعه",
        },
        c8: {
          t1: "تم التسجيل في ضريبة السلع الانتقائية بنجاح",
          t2:
            "تقر الهيئة العامة للزكاة والدخل بتسجيلك في ضريبة السلع الانتقائية",
          t3: "الاسم",
          t4: "Ahmad Muhammed",
          t5: "رقم الطلب",
          t6: "1234567890",
          t7: "التاريخ:",
          t8: "23/6/2020",
          t9:
            "يرجى الاحتفاظ برقم الطلب للرجوع إليه والتواصل من خلاله . ستقوم الهيئة بمعالجة الطلب الخاص بك  . لمزيد من المعلومات ، يرجى الاتصال بخدمة العملاء",
          btn: "تنزيل الإقرار",
          btn2: "الذهاب إلى لوحة التحكم",
        },
      },
    },
  },
};
